remote_theme: pmarsceill/just-the-docs
theme: "just-the-docs"

# used by just-the-docs
title: Goaliath
# description: to do
search_enabled: false
# Aux links for the upper right navigation -> moved to _data file
aux_links_new_tab: true

plugins:
  - jekyll-polyglot

# jekyll-polyglot
languages: ["en", "es"]
default_lang: "en"
parallel_localization: false
sass:  # workaround for https://github.com/untra/polyglot/issues/125
  sourcemap: never